apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-grpc-server.fullname" . }}
  labels:
    {{- include "hello-grpc-server.labels" . | nindent 4 }}
spec:
  # type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 50051
      protocol: TCP
      name: grpc
  selector:
    {{- include "hello-grpc-server.selectorLabels" . | nindent 4 }}
